[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "Full"
opacity = 0.7
dimensions = { columns = 0, lines = 0 }
title = "Alacritty"

[scrolling]
history = 10000 
multiplier = 3 

[font]
normal = { family = "Hack", style = "Italic" }
size = 16 

[cursor]
style = { "shape" = "Block",blinking = "On"}

[terminal]
shell = { program = "/bin/bash", args = ["-l"] }
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", mods = "Control|Shift", action = "Paste" }
]

[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" }
]

[colors]
[colors.primary]
foreground = "#c5c8c6"
background = "#1d1f21"

[colors.normal]
black   = "#282a2e"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#abb2bf"

[colors.bright]
black   = "#4b5263"
red     = "#f07178"
green   = "#aad75c"
yellow  = "#fdd835"
blue    = "#82aaff"
magenta = "#d4b8e5"
cyan    = "#79dac8"
white   = "#ffffff"
