[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "Full"
opacity = 0.7
dimensions = { columns = 0, lines = 0 }
title = "Alacritty"

[scrolling]
history = 10000 
multiplier = 3 

[font]
normal = { family = "Hack", style = "Italic" }
size = 16 

[cursor]
style = { "shape" = "Block",blinking = "On"}

[terminal]
shell = { program = "/bin/bash", args = ["-l"] }
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = false
bindings = [
  { mouse = "Right", mods = "Control|Shift", action = "Paste" }
]

[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" }
]

[colors]
[colors.primary]
foreground = "#c5c8c6"
background = "#1d1f21"

[colors.normal]
black   = "#282a2e"
red     = "#a54242"
green   = "#8c9440"
yellow  = "#de935f"
blue    = "#5f819d"
magenta = "#85678f"
cyan    = "#5e8d87"
white   = "#707880"

[colors.bright]
black   = "#373b41"
red     = "#cc6666"
green   = "#b5bd68"
yellow  = "#f0c674"
blue    = "#81a2be"
magenta = "#b294bb"
cyan    = "#8abeb7"
white   = "#c5c8c6"
