[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Z","threads=8"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-Z","threads=8"]
