[observability]
log-level = "info"
observation-path = "/var/run/ntpd-rs/observe"

[source-defaults]
poll-interval-limits = { min = 30 , max = 60 } 
initial-poll-interval = 3

[[source]]
mode = "pool"
ntp-version = 4
address = "cn.pool.ntp.org"
count = 5

[synchronization]
single-step-panic-threshold = 1000
startup-step-panic-threshold = 2000
accumulated-step-panic-threshold = 1800
minimum-agreeing-sources = 3
