ipv4 = ""
dhcp = false
hostname = "hostname"
listeners = [
    "udp://0.0.0.0:11010",
    "tcp://0.0.0.0:11010"
]
rpc_portal = "127.0.0.1:15888"

[network_identity]
network_name = "name"
network_secret = "secret" 

[flags]
enable_ipv6 = false
multi_thread = false
private_mode = true
